name: Go
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Load database tables
        run: docker exec -i mysql mysql -uroot  -psecret  test < ./001_create_tables.sql
        working-directory: sql
      - name: Load database procedures
        run: docker exec -i mysql mysql -uroot  -psecret  test < ./002_create_store_procedures.sql
        working-directory: sql
      - name: Load database test data
        run: docker exec -i mysql mysql -uroot  -psecret  test < ./003_populate_test_data.sql
        working-directory: sql
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...